
export interface LocationData {
  states: {
    state: string;
    cities: {
      city: string;
      areas: string[];
    }[];
  }[];
}

export const NIGERIA_LOCATIONS: LocationData = {
  "states": [
    {
      "state": "Abia",
      "cities": [
        { "city": "Aba North", "areas": [] },
        { "city": "Aba South", "areas": [] },
        { "city": "Arochukwu", "areas": [] },
        { "city": "Bende", "areas": [] },
        { "city": "Ikwuano", "areas": [] },
        { "city": "Isiala Ngwa North", "areas": [] },
        { "city": "Isiala Ngwa South", "areas": [] },
        { "city": "Isiukwuato", "areas": [] },
        { "city": "Obi Ngwa", "areas": [] },
        { "city": "Ohafia", "areas": [] },
        { "city": "Osisioma", "areas": [] },
        { "city": "Ugwunagbo", "areas": [] },
        { "city": "Ukwa East", "areas": [] },
        { "city": "Ukwa West", "areas": [] },
        { "city": "Umuahia North", "areas": [] },
        { "city": "Umuahia South", "areas": [] },
        { "city": "Umunneochi", "areas": [] }
      ]
    },
    {
      "state": "Adamawa",
      "cities": [
        { "city": "Yola North", "areas": [] },
        { "city": "Yola South", "areas": [] },
        { "city": "Demsa", "areas": [] },
        { "city": "Fufore", "areas": [] },
        { "city": "Ganye", "areas": [] },
        { "city": "Girei", "areas": [] },
        { "city": "Gombi", "areas": [] },
        { "city": "Guyuk", "areas": [] },
        { "city": "Hong", "areas": [] },
        { "city": "Jada", "areas": [] },
        { "city": "Lamurde", "areas": [] },
        { "city": "Madagali", "areas": [] },
        { "city": "Maiha", "areas": [] },
        { "city": "Mayo-Belwa", "areas": [] },
        { "city": "Michika", "areas": [] },
        { "city": "Mubi North", "areas": [] },
        { "city": "Mubi South", "areas": [] },
        { "city": "Numan", "areas": [] },
        { "city": "Shelleng", "areas": [] },
        { "city": "Song", "areas": [] },
        { "city": "Toungo", "areas": [] }
      ]
    },
    {
      "state": "Akwa Ibom",
      "cities": [
        { "city": "Abak", "areas": [] },
        { "city": "Eastern Obolo", "areas": [] },
        { "city": "Eket", "areas": [] },
        { "city": "Esit Eket", "areas": [] },
        { "city": "Essien Udim", "areas": [] },
        { "city": "Etim Ekpo", "areas": [] },
        { "city": "Etinan", "areas": [] },
        { "city": "Ibeno", "areas": [] },
        { "city": "Ibesikpo Asutan", "areas": [] },
        { "city": "Ibiono-Ibom", "areas": [] },
        { "city": "Ika", "areas": [] },
        { "city": "Ikono", "areas": [] },
        { "city": "Ikot Ekpene", "areas": [] },
        { "city": "Ikot-Abasi", "areas": [] },
        { "city": "Ini", "areas": [] },
        { "city": "Itu", "areas": [] },
        { "city": "Mbo", "areas": [] },
        { "city": "Mkpat-Enin", "areas": [] },
        { "city": "Nsit-Atai", "areas": [] },
        { "city": "Nsit-Ibom", "areas": [] },
        { "city": "Nsit-Ubium", "areas": [] },
        { "city": "Obot-Akara", "areas": [] },
        { "city": "Okobo", "areas": [] },
        { "city": "Onna", "areas": [] },
        { "city": "Oron", "areas": [] },
        { "city": "Oruk Anam", "areas": [] },
        { "city": "Udung-Uko", "areas": [] },
        { "city": "Ukanafun", "areas": [] },
        { "city": "Uruan", "areas": [] },
        { "city": "Urue-Offong/Oruko", "areas": [] },
        { "city": "Uyo", "areas": [] }
      ]
    },
    {
      "state": "Anambra",
      "cities": [
        { "city": "Awka", "areas": [] },
        { "city": "Idemili", "areas": [] },
        { "city": "Nnewi", "areas": [] },
        { "city": "Onitsha", "areas": [] },
        { "city": "Aghamelu", "areas": [] },
        { "city": "Aguata", "areas": [] },
        { "city": "Anambra East", "areas": [] },
        { "city": "Anambra West", "areas": [] },
        { "city": "Anaocha", "areas": [] },
        { "city": "Ayamelum", "areas": [] },
        { "city": "Dunukofia", "areas": [] },
        { "city": "Ekwusigo", "areas": [] },
        { "city": "Ihiala", "areas": [] },
        { "city": "Njikoka", "areas": [] },
        { "city": "Ogbaru", "areas": [] },
        { "city": "Orumba", "areas": [] },
        { "city": "Oyi", "areas": [] }
      ]
    },
    {
      "state": "Bauchi",
      "cities": [
        { "city": "Bauchi LGA", "areas": [] },
        { "city": "Bogoro", "areas": [] },
        { "city": "Alkaleri", "areas": [] },
        { "city": "Damban", "areas": [] },
        { "city": "Darazo", "areas": [] },
        { "city": "Dass", "areas": [] },
        { "city": "Gamawa", "areas": [] },
        { "city": "Ganjuwa", "areas": [] },
        { "city": "Giade", "areas": [] },
        { "city": "Itas/Gadau", "areas": [] },
        { "city": "Jama'are", "areas": [] },
        { "city": "Katagum", "areas": [] },
        { "city": "Kirfi", "areas": [] },
        { "city": "Misau", "areas": [] },
        { "city": "Ningi", "areas": [] },
        { "city": "Shira", "areas": [] },
        { "city": "Toro", "areas": [] },
        { "city": "Warji", "areas": [] },
        { "city": "Zaki", "areas": [] }
      ]
    },
    {
      "state": "Bayelsa",
      "cities": [
        { "city": "Yenagoa", "areas": [] },
        { "city": "Brass", "areas": [] },
        { "city": "Ekeremor", "areas": [] },
        { "city": "Kolokuma/Opokuma", "areas": [] },
        { "city": "Nembe", "areas": [] },
        { "city": "Ogbia", "areas": [] },
        { "city": "Sagbama", "areas": [] },
        { "city": "Southern Ijaw", "areas": [] }
      ]
    },
    {
      "state": "Benue",
      "cities": [
        { "city": "Gboko", "areas": [] },
        { "city": "Katsina-Ala", "areas": [] },
        { "city": "Makurdi", "areas": [] },
        { "city": "Otukpo", "areas": [] },
        { "city": "Ado", "areas": [] },
        { "city": "Agatu", "areas": [] },
        { "city": "Apa", "areas": [] },
        { "city": "Buruku", "areas": [] },
        { "city": "Guma", "areas": [] },
        { "city": "Gwer", "areas": [] },
        { "city": "Konshisha", "areas": [] },
        { "city": "Kwande", "areas": [] },
        { "city": "Konshisha", "areas": [] },
        { "city": "Kwande", "areas": [] },
        { "city": "Logo", "areas": [] },
        { "city": "Obi", "areas": [] },
        { "city": "Ogbadibo", "areas": [] },
        { "city": "Ohimini", "areas": [] },
        { "city": "Oju", "areas": [] },
        { "city": "Okpokwu", "areas": [] },
        { "city": "Tarka", "areas": [] },
        { "city": "Ukum", "areas": [] },
        { "city": "Ushongo", "areas": [] },
        { "city": "Vandeikya", "areas": [] }
      ]
    },
    {
      "state": "Borno",
      "cities": [
        { "city": "Maiduguri", "areas": [] },
        { "city": "Abadam", "areas": [] },
        { "city": "Askira/Uba", "areas": [] },
        { "city": "Bama", "areas": [] },
        { "city": "Bayo", "areas": [] },
        { "city": "Biu", "areas": [] },
        { "city": "Chibok", "areas": [] },
        { "city": "Damboa", "areas": [] },
        { "city": "Dikwa", "areas": [] },
        { "city": "Gubio", "areas": [] },
        { "city": "Guzamala", "areas": [] },
        { "city": "Gwoza", "areas": [] },
        { "city": "Hawul", "areas": [] },
        { "city": "Jere", "areas": [] },
        { "city": "Kaga", "areas": [] },
        { "city": "Kala/Balge", "areas": [] },
        { "city": "Konduga", "areas": [] },
        { "city": "Kukawa", "areas": [] },
        { "city": "Kwaya Kusar", "areas": [] },
        { "city": "Mafa", "areas": [] },
        { "city": "Magumeri", "areas": [] },
        { "city": "Marte", "areas": [] },
        { "city": "Mobbar", "areas": [] },
        { "city": "Monguno", "areas": [] },
        { "city": "Ngala", "areas": [] },
        { "city": "Nganzai", "areas": [] },
        { "city": "Shani", "areas": [] }
      ]
    },
    {
      "state": "Cross River",
      "cities": [
        { "city": "Calabar", "areas": [] },
        { "city": "Ikom", "areas": [] },
        { "city": "Ogoja", "areas": [] },
        { "city": "Abi", "areas": [] },
        { "city": "Akamkpa", "areas": [] },
        { "city": "Akpabuyo", "areas": [] },
        { "city": "Bakassi", "areas": [] },
        { "city": "Bekwara", "areas": [] },
        { "city": "Biase", "areas": [] },
        { "city": "Boki", "areas": [] },
        { "city": "Etung", "areas": [] },
        { "city": "Obanliku", "areas": [] },
        { "city": "Obubra", "areas": [] },
        { "city": "Obudu", "areas": [] },
        { "city": "Odukpani", "areas": [] },
        { "city": "Yakuur", "areas": [] },
        { "city": "Yala", "areas": [] }
      ]
    },
    {
      "state": "Delta",
      "cities": [
        { "city": "Oshimili South", "areas": [] },
        { "city": "Sapele", "areas": [] },
        { "city": "Ugheli", "areas": [] },
        { "city": "Uvwie", "areas": [] },
        { "city": "Warri", "areas": [] },
        { "city": "Aniocha North", "areas": [] },
        { "city": "Aniocha South", "areas": [] },
        { "city": "Bomadi", "areas": [] },
        { "city": "Burutu", "areas": [] },
        { "city": "Ethiope East", "areas": [] },
        { "city": "Ethiope West", "areas": [] },
        { "city": "Ika North East", "areas": [] },
        { "city": "Ika South", "areas": [] },
        { "city": "Isoko", "areas": [] },
        { "city": "Ndokwa East", "areas": [] },
        { "city": "Ndokwa West", "areas": [] },
        { "city": "Okpe", "areas": [] },
        { "city": "Oshimili North", "areas": [] },
        { "city": "Patani", "areas": [] },
        { "city": "Udu", "areas": [] },
        { "city": "Ukwuani", "areas": [] }
      ]
    },
    {
      "state": "Ebonyi",
      "cities": [
        { "city": "Abakaliki", "areas": [] },
        { "city": "Afikpo North", "areas": [] },
        { "city": "Afikpo South", "areas": [] },
        { "city": "Ebonyi", "areas": [] },
        { "city": "Ezza", "areas": [] },
        { "city": "Ikwo", "areas": [] },
        { "city": "Ishielu", "areas": [] },
        { "city": "Ivo", "areas": [] },
        { "city": "Izzi", "areas": [] },
        { "city": "Ohaozara", "areas": [] },
        { "city": "Ohaukwu", "areas": [] },
        { "city": "Onicha", "areas": [] }
      ]
    },
    {
      "state": "Edo",
      "cities": [
        { "city": "Benin City", "areas": [] },
        { "city": "Egor", "areas": [] },
        { "city": "Ekpoma", "areas": [] },
        { "city": "Ikpoba-Okha", "areas": [] },
        { "city": "Okada", "areas": [] },
        { "city": "Akoko-Edo", "areas": [] },
        { "city": "Auchi", "areas": [] },
        { "city": "Esan North East", "areas": [] },
        { "city": "Fugar", "areas": [] },
        { "city": "Igueben", "areas": [] },
        { "city": "Irrua", "areas": [] },
        { "city": "Orhionmwon", "areas": [] },
        { "city": "Ovia South", "areas": [] },
        { "city": "Owan", "areas": [] },
        { "city": "Ubiaja", "areas": [] },
        { "city": "Uhunmwonde", "areas": [] }
      ]
    },
    {
      "state": "Ekiti",
      "cities": [
        { "city": "Ado Ekiti", "areas": [] },
        { "city": "Ido-Osi", "areas": [] },
        { "city": "Ikere", "areas": [] },
        { "city": "Ikole", "areas": [] },
        { "city": "Ilawe", "areas": [] },
        { "city": "Aiyekire (Gbonyin)", "areas": [] },
        { "city": "Aramoko", "areas": [] },
        { "city": "Efon", "areas": [] },
        { "city": "Emure", "areas": [] },
        { "city": "Ijero", "areas": [] },
        { "city": "Ilejemeje", "areas": [] },
        { "city": "Irepodun/Ifelodun", "areas": [] },
        { "city": "Ise/Orun", "areas": [] },
        { "city": "Moba", "areas": [] },
        { "city": "Omuo", "areas": [] },
        { "city": "Oye", "areas": [] }
      ]
    },
    {
      "state": "Enugu",
      "cities": [
        { "city": "Enugu", "areas": [] },
        { "city": "Nkanu West", "areas": [] },
        { "city": "Nsukka", "areas": [] },
        { "city": "Udi", "areas": [] },
        { "city": "Aninri", "areas": [] },
        { "city": "Awgu", "areas": [] },
        { "city": "Ezeagu", "areas": [] },
        { "city": "Igbo Eze South", "areas": [] },
        { "city": "Igbo-Etiti", "areas": [] },
        { "city": "Igbo-Eze North", "areas": [] },
        { "city": "Isi-Uzo", "areas": [] },
        { "city": "Nkanu East", "areas": [] },
        { "city": "Oji-River", "areas": [] },
        { "city": "Udenu", "areas": [] },
        { "city": "Uzo-Uwani", "areas": [] }
      ]
    },
    {
      "state": "Gombe",
      "cities": [
        { "city": "Gombe LGA", "areas": [] },
        { "city": "Akko", "areas": [] },
        { "city": "Balanga", "areas": [] },
        { "city": "Billiri", "areas": [] },
        { "city": "Dukku", "areas": [] },
        { "city": "Funakaye", "areas": [] },
        { "city": "Kaltungo", "areas": [] },
        { "city": "Kwami", "areas": [] },
        { "city": "Nafada", "areas": [] },
        { "city": "Shomgom", "areas": [] },
        { "city": "Yamaltu/Deba", "areas": [] }
      ]
    },
    {
      "state": "Imo",
      "cities": [
        { "city": "Ikeduru", "areas": [] },
        { "city": "Mbaitoli", "areas": [] },
        { "city": "Okigwe", "areas": [] },
        { "city": "Orlu", "areas": [] },
        { "city": "Owerri", "areas": [] },
        { "city": "Aboh-Mbaise", "areas": [] },
        { "city": "Ahiazu-Mbaise", "areas": [] },
        { "city": "Ehime-Mbano", "areas": [] },
        { "city": "Ezinihitte", "areas": [] },
        { "city": "Ezinihitte Mbaise", "areas": [] },
        { "city": "Ideato North", "areas": [] },
        { "city": "Ideato South", "areas": [] },
        { "city": "Ihitte/Uboma", "areas": [] },
        { "city": "Isiala Mbano", "areas": [] },
        { "city": "Isu", "areas": [] },
        { "city": "Ngor-Okpala", "areas": [] },
        { "city": "Njaba", "areas": [] },
        { "city": "Nkwerre", "areas": [] },
        { "city": "Nwangele", "areas": [] },
        { "city": "Obowo", "areas": [] },
        { "city": "Oguta", "areas": [] },
        { "city": "Ohaji/Egbema", "areas": [] },
        { "city": "Onuimo", "areas": [] },
        { "city": "Orsu", "areas": [] },
        { "city": "Oru", "areas": [] }
      ]
    },
    {
      "state": "Jigawa",
      "cities": [
        { "city": "Dutse-Jigawa", "areas": [] },
        { "city": "Garki", "areas": [] },
        { "city": "Auyo", "areas": [] },
        { "city": "Babura", "areas": [] },
        { "city": "Biriniwa", "areas": [] },
        { "city": "Buji", "areas": [] },
        { "city": "Gagarawa", "areas": [] },
        { "city": "Gumel", "areas": [] },
        { "city": "Guri", "areas": [] },
        { "city": "Gwaram", "areas": [] },
        { "city": "Gwiwa", "areas": [] },
        { "city": "Hadejia", "areas": [] },
        { "city": "Jahun", "areas": [] },
        { "city": "Kafin Hausa", "areas": [] },
        { "city": "Kaugama", "areas": [] },
        { "city": "Kazaure", "areas": [] },
        { "city": "Kiri Kasamma", "areas": [] },
        { "city": "Kiyawa", "areas": [] },
        { "city": "Maigatari", "areas": [] },
        { "city": "Malam Madori", "areas": [] },
        { "city": "Miga", "areas": [] },
        { "city": "Ringim", "areas": [] },
        { "city": "Roni", "areas": [] },
        { "city": "Sule-Tankarkar", "areas": [] },
        { "city": "Taura", "areas": [] },
        { "city": "Yankwashi", "areas": [] }
      ]
    },
    {
      "state": "Kaduna",
      "cities": [
        { "city": "Chikun", "areas": [] },
        { "city": "Igabi", "areas": [] },
        { "city": "Kaduna / Kaduna State", "areas": [] },
        { "city": "Zaria", "areas": [] },
        { "city": "Birnin-Gwari", "areas": [] },
        { "city": "Giwa", "areas": [] },
        { "city": "Ikara", "areas": [] },
        { "city": "Jaba", "areas": [] },
        { "city": "Jema'a", "areas": [] },
        { "city": "Kachia", "areas": [] },
        { "city": "Kagarko", "areas": [] },
        { "city": "Kajuru", "areas": [] },
        { "city": "Kaura-Kaduna", "areas": [] },
        { "city": "Kauru", "areas": [] },
        { "city": "Kubau", "areas": [] },
        { "city": "Kudan", "areas": [] },
        { "city": "Lere", "areas": [] },
        { "city": "Makarfi", "areas": [] },
        { "city": "Sanga", "areas": [] },
        { "city": "Soba", "areas": [] },
        { "city": "Zango-Kataf", "areas": [] }
      ]
    },
    {
      "state": "Kano",
      "cities": [
        { "city": "Fagge", "areas": [] },
        { "city": "Kano Municipal", "areas": [] },
        { "city": "Nasarawa-Kano", "areas": [] },
        { "city": "Tarauni", "areas": [] },
        { "city": "Ajingi", "areas": [] },
        { "city": "Albasu", "areas": [] },
        { "city": "Bagwai", "areas": [] },
        { "city": "Bebeji", "areas": [] },
        { "city": "Bichi", "areas": [] },
        { "city": "Bunkure", "areas": [] },
        { "city": "Dala", "areas": [] },
        { "city": "Dambatta", "areas": [] },
        { "city": "Dawakin Kudu", "areas": [] },
        { "city": "Dawakin Tofa", "areas": [] },
        { "city": "Doguwa", "areas": [] },
        { "city": "Gabasawa", "areas": [] },
        { "city": "Garko", "areas": [] },
        { "city": "Garum Mallam", "areas": [] },
        { "city": "Garun Mallam", "areas": [] },
        { "city": "Gaya", "areas": [] },
        { "city": "Gezawa", "areas": [] },
        { "city": "Gwale", "areas": [] },
        { "city": "Gwarzo", "areas": [] },
        { "city": "Kabo", "areas": [] },
        { "city": "Karaye", "areas": [] },
        { "city": "Kibiya", "areas": [] },
        { "city": "Kiru", "areas": [] },
        { "city": "Kumbotso", "areas": [] },
        { "city": "Kunchi", "areas": [] },
        { "city": "Kura", "areas": [] },
        { "city": "Madobi", "areas": [] },
        { "city": "Makoda", "areas": [] },
        { "city": "Minjibir", "areas": [] },
        { "city": "Rano", "areas": [] },
        { "city": "Rimin Gado", "areas": [] },
        { "city": "Rogo", "areas": [] },
        { "city": "Shanono", "areas": [] },
        { "city": "Sumaila", "areas": [] },
        { "city": "Takai", "areas": [] },
        { "city": "Tofa", "areas": [] },
        { "city": "Tsanyawa", "areas": [] },
        { "city": "Tudun Wada", "areas": [] },
        { "city": "Ungogo", "areas": [] },
        { "city": "Warawa", "areas": [] },
        { "city": "Wudil", "areas": [] }
      ]
    },
    {
      "state": "Katsina",
      "cities": [
        { "city": "Danja", "areas": [] },
        { "city": "Daura", "areas": [] },
        { "city": "Katsina", "areas": [] },
        { "city": "Zango", "areas": [] },
        { "city": "Bakori", "areas": [] },
        { "city": "Batagarawa", "areas": [] },
        { "city": "Batsari", "areas": [] },
        { "city": "Baure", "areas": [] },
        { "city": "Bindawa", "areas": [] },
        { "city": "Charanchi", "areas": [] },
        { "city": "Dan Musa", "areas": [] },
        { "city": "Dandume", "areas": [] },
        { "city": "Dutsi", "areas": [] },
        { "city": "Dutsin-Ma", "areas": [] },
        { "city": "Faskari", "areas": [] },
        { "city": "Funtua", "areas": [] },
        { "city": "Ingawa", "areas": [] },
        { "city": "Jibia", "areas": [] },
        { "city": "Kafur", "areas": [] },
        { "city": "Kaita", "areas": [] },
        { "city": "Kankara", "areas": [] },
        { "city": "Kankia", "areas": [] },
        { "city": "Kurfi", "areas": [] },
        { "city": "Kusada", "areas": [] },
        { "city": "Mai'adua", "areas": [] },
        { "city": "Malumfashi", "areas": [] },
        { "city": "Mani", "areas": [] },
        { "city": "Mashi", "areas": [] },
        { "city": "Matazu", "areas": [] },
        { "city": "Musawa", "areas": [] },
        { "city": "Rimi", "areas": [] },
        { "city": "Sabuwa", "areas": [] },
        { "city": "Safana", "areas": [] },
        { "city": "Sandamu", "areas": [] }
      ]
    },
    {
      "state": "Kebbi",
      "cities": [
        { "city": "Birnin Kebbi", "areas": [] },
        { "city": "Jega", "areas": [] },
        { "city": "Zuru", "areas": [] },
        { "city": "Aleiro", "areas": [] },
        { "city": "Arewa-Dandi", "areas": [] },
        { "city": "Argungu", "areas": [] },
        { "city": "Augie", "areas": [] },
        { "city": "Bagudo", "areas": [] },
        { "city": "Bunza", "areas": [] },
        { "city": "Dandi", "areas": [] },
        { "city": "Fakai", "areas": [] },
        { "city": "Gwandu", "areas": [] },
        { "city": "Kalgo", "areas": [] },
        { "city": "Koko/Besse", "areas": [] },
        { "city": "Maiyama", "areas": [] },
        { "city": "Ngaski", "areas": [] },
        { "city": "Sakaba", "areas": [] },
        { "city": "Shanga", "areas": [] },
        { "city": "Suru", "areas": [] },
        { "city": "Wasagu/Danko", "areas": [] },
        { "city": "Yauri", "areas": [] }
      ]
    },
    {
      "state": "Kogi",
      "cities": [
        { "city": "Lokoja", "areas": [] },
        { "city": "Okene", "areas": [] },
        { "city": "Adavi", "areas": [] },
        { "city": "Ajaokuta", "areas": [] },
        { "city": "Ankpa", "areas": [] },
        { "city": "Bassa", "areas": [] },
        { "city": "Dekina", "areas": [] },
        { "city": "Ibaji", "areas": [] },
        { "city": "Idah", "areas": [] },
        { "city": "Igala Mela", "areas": [] },
        { "city": "Igalamela-Odolu", "areas": [] },
        { "city": "Ijumu", "areas": [] },
        { "city": "Kabba/Bunu", "areas": [] },
        { "city": "Kogi LGA", "areas": [] },
        { "city": "Koton Karfe", "areas": [] },
        { "city": "Mopa-Muro", "areas": [] },
        { "city": "Ofu", "areas": [] },
        { "city": "Ogori/Magongo", "areas": [] },
        { "city": "Okehi", "areas": [] },
        { "city": "Olamaboro", "areas": [] },
        { "city": "Omala", "areas": [] },
        { "city": "Yagba East", "areas": [] },
        { "city": "Yagba West", "areas": [] }
      ]
    },
    {
      "state": "Kwara",
      "cities": [
        { "city": "Ilorin East", "areas": [] },
        { "city": "Ilorin South", "areas": [] },
        { "city": "Ilorin West", "areas": [] },
        { "city": "Asa", "areas": [] },
        { "city": "Baruten", "areas": [] },
        { "city": "Edu", "areas": [] },
        { "city": "Ekiti-Kwara", "areas": [] },
        { "city": "Ifelodun-Kwara", "areas": [] },
        { "city": "Irepodun-Kwara", "areas": [] },
        { "city": "Isin", "areas": [] },
        { "city": "Kaiama", "areas": [] },
        { "city": "Moro", "areas": [] },
        { "city": "Offa", "areas": [] },
        { "city": "Oke-Ero", "areas": [] },
        { "city": "Oyun", "areas": [] },
        { "city": "Pategi", "areas": [] }
      ]
    },
    {
      "state": "Lagos",
      "cities": [
        { "city": "Ajah", "areas": ["Ado", "Badore", "Lafiaji", "Sangotedo", "Ogombo", "Awoyaya", "Abraham Adesanya"] },
        { "city": "Alimosho", "areas": ["Egbeda", "Akowonjo", "Dopemu", "Idimu", "Ikotun", "Shasha", "Isheri Olofin", "Egan", "Ijegun", "Egbe", "Iyana Ipaja"] },
        { "city": "Ikeja", "areas": ["Alausa", "Opebi", "Allen Avenue", "GRA", "Maryland", "Agidingbi", "Ogba", "Oregun"] },
        { "city": "Ojo", "areas": ["Alaba", "Iba", "Ajangbadi", "Okokomaiko", "Abule-Ado", "Satellite Town", "Festac"] },
        { "city": "Surulere", "areas": ["Aguda", "Iponri", "Bode Thomas", "Ojuelegba", "Lawanson", "Shitta", "Akerele", "Eric Moore"] },
        { "city": "Abule Egba", "areas": ["Ekoro", "Meiran", "New Oko-Oba", "Abattoir", "Kola", "Command"] },
        { "city": "Agbara-Igbesan", "areas": [] },
        { "city": "Agboyi/Ketu", "areas": ["Alapere", "Agboyi", "Owode Onirin", "Ketu", "Ajegunle", "Ikosi"] },
        { "city": "Agege", "areas": ["Dopemu", "Oko-Oba", "Ogba", "Pen Cinema", "Isale Oja"] },
        { "city": "Amuwo-Odofin", "areas": ["Festac Town", "Satellite Town", "Navy Town", "Amuwo", "Abule-Ado"] },
        { "city": "Apapa", "areas": ["Apapa GRA", "Liverpool Road", "Creek Road", "Marine Road", "Wharf Road"] },
        { "city": "Badagry", "areas": ["Seme Border", "Ibereko", "Ajido", "Ilogbo", "Iyana Era"] },
        { "city": "Egbe/Idimu", "areas": ["Ikotun", "Egbeda", "Shasha", "Idimu", "Egbe"] },
        { "city": "Ejigbo", "areas": ["Jakande Estate", "Oke Afa", "Iyana Ejigbo", "Navy Estate", "Isolo"] },
        { "city": "Eko Atlantic", "areas": ["Eko Pearl Towers", "Azuri Peninsula", "Business District", "Harbor Front"] },
        { "city": "Epe", "areas": ["Ita Opo", "Eredo", "Ayetoro", "Poka", "Agbowa"] },
        { "city": "Gbagada", "areas": ["Ifako", "Phase 1", "Phase 2", "Soluyi", "Pedro"] },
        { "city": "Ibeju", "areas": ["Eleko", "Awoyaya", "Lakowe", "Bogije", "Ode Omi"] },
        { "city": "Ifako-Ijaiye", "areas": ["Iju", "Ogba", "Pen Cinema", "Fagba", "Ishaga"] },
        { "city": "Ikorodu", "areas": ["Igbogbo", "Bayeku", "Ebute", "Agbede", "Owode", "Majidun"] },
        { "city": "Ikotun/Igando", "areas": ["Igando", "Ikotun", "Egbe", "Akesan", "Abaranje"] },
        { "city": "Ikoyi", "areas": ["Banana Island", "Bourdillon", "Gerrard Road", "Osborne", "Parkview Estate"] },
        { "city": "Ilashe", "areas": [] },
        { "city": "Ilupeju", "areas": ["Town Planning", "Coker Road", "Industrial Avenue", "Palmgrove"] },
        { "city": "Ipaja", "areas": ["Ayobo", "Baruwa", "Command", "Alagolo", "Megida"] },
        { "city": "Isolo", "areas": ["Ajao Estate", "Oke Afa", "Mafoluku", "Ejigbo"] },
        { "city": "Kosofe", "areas": ["Ketu", "Alapere", "Ojota", "Agboyi", "Ajegunle"] },
        { "city": "Lagos Island (Eko)", "areas": ["Idumota", "Oluwole", "Tinubu Square", "Balogun", "Elegbata"] },
        { "city": "Lekki", "areas": ["Chevron Drive", "Ikate", "Lekki Phase 1", "Lekki Phase 2", "Ajah", "Victoria Garden City (VGC)"] },
        { "city": "Magodo", "areas": ["Phase 1", "Phase 2", "Shangisha", "CMD Road"] },
        { "city": "Maryland", "areas": ["Mende", "Anthony", "Ikeja GRA"] },
        { "city": "Mushin", "areas": ["Idi Oro", "Olosha", "Papa Ajao", "Ilasamaja"] },
        { "city": "Ogba", "areas": ["Aguda", "Oke-Ira", "Iju Road"] },
        { "city": "Ogudu", "areas": ["Ojota", "Ogudu GRA", "Ori-Oke"] },
        { "city": "Ojodu", "areas": ["Berger", "Yakoyo", "Olomore"] },
        { "city": "Ojota", "areas": ["Ogudu", "Kosofe", "Oregun"] },
        { "city": "Orile", "areas": ["Iganmu", "Coker", "Amukoko"] },
        { "city": "Oshodi", "areas": ["Oshodi-Isolo", "Mafoluku", "Oke-Afa"] },
        { "city": "Shomolu", "areas": ["Bariga", "Akoka", "Pedro", "Onipanu"] },
        { "city": "Tarkwa Bay Island", "areas": [] },
        { "city": "Victoria Island", "areas": ["Ozumba Mbadiwe", "Sanusi Fafunwa", "Kofo Abayomi", "Eko Hotel", "Tiamiyu Savage"] },
        { "city": "Yaba", "areas": ["Abule-Ijesha", "Sabo", "Makoko", "Fola Agoro", "Iwaya", "Jibowu", "Tejuosho"] }
      ]
    },
    {
      "state": "Nasarawa",
      "cities": [
        { "city": "Karu-Nasarawa", "areas": [] },
        { "city": "Keffi", "areas": [] },
        { "city": "Lafia", "areas": [] },
        { "city": "Akwanga", "areas": [] },
        { "city": "Awe", "areas": [] },
        { "city": "Doma", "areas": [] },
        { "city": "Keana", "areas": [] },
        { "city": "Kokona", "areas": [] },
        { "city": "Nasarawa", "areas": [] },
        { "city": "Nasarawa-Eggon", "areas": [] },
        { "city": "Obi-Nasarawa", "areas": [] },
        { "city": "Toto", "areas": [] },
        { "city": "Wamba", "areas": [] }
      ]
    },
    {
      "state": "Niger",
      "cities": [
        { "city": "Bida", "areas": [] },
        { "city": "Bosso", "areas": [] },
        { "city": "Chanchaga", "areas": [] },
        { "city": "Minna", "areas": [] },
        { "city": "Suleja", "areas": [] },
        { "city": "Agaie", "areas": [] },
        { "city": "Agwara", "areas": [] },
        { "city": "Borgu", "areas": [] },
        { "city": "Edati", "areas": [] },
        { "city": "Gbako", "areas": [] },
        { "city": "Gurara", "areas": [] },
        { "city": "Katcha", "areas": [] },
        { "city": "Kontagora", "areas": [] },
        { "city": "Lapai", "areas": [] },
        { "city": "Lavun", "areas": [] },
        { "city": "Magama", "areas": [] },
        { "city": "Mariga", "areas": [] },
        { "city": "Mashegu", "areas": [] },
        { "city": "Mokwa", "areas": [] },
        { "city": "Muya", "areas": [] },
        { "city": "Paikoro", "areas": [] },
        { "city": "Rafi", "areas": [] },
        { "city": "Rijau", "areas": [] },
        { "city": "Shiroro", "areas": [] },
        { "city": "Tafa", "areas": [] },
        { "city": "Wushishi", "areas": [] }
      ]
    },
    {
      "state": "Ogun",
      "cities": [
        { "city": "Abeokuta South", "areas": [] },
        { "city": "Ado-Odo/Ota", "areas": [] },
        { "city": "Ijebu Ode", "areas": [] },
        { "city": "Obafemi-Owode", "areas": [] },
        { "city": "Sagamu", "areas": [] },
        { "city": "Abeokuta North", "areas": [] },
        { "city": "Ayetoro", "areas": [] },
        { "city": "Ewekoro", "areas": [] },
        { "city": "Ifo", "areas": [] },
        { "city": "Ijebu", "areas": [] },
        { "city": "Ikenne", "areas": [] },
        { "city": "Ilaro", "areas": [] },
        { "city": "Imeko Afon", "areas": [] },
        { "city": "Ipokia", "areas": [] },
        { "city": "Iseri", "areas": [] },
        { "city": "Odeda", "areas": [] },
        { "city": "Odogbolu", "areas": [] },
        { "city": "Ogun Waterside", "areas": [] },
        { "city": "Pakuro", "areas": [] },
        { "city": "Remo North", "areas": [] }
      ]
    },
    {
      "state": "Ondo",
      "cities": [
        { "city": "Akure", "areas": [] },
        { "city": "Iju/Itaogbolu", "areas": [] },
        { "city": "Okitipupa", "areas": [] },
        { "city": "Ondo", "areas": [] },
        { "city": "Owo", "areas": [] },
        { "city": "Akungba", "areas": [] },
        { "city": "Ese-Odo", "areas": [] },
        { "city": "Idanre", "areas": [] },
        { "city": "Ifedore", "areas": [] },
        { "city": "Ikare Akoko", "areas": [] },
        { "city": "Ilaje", "areas": [] },
        { "city": "Ile-Oluji-Okeigbo", "areas": [] },
        { "city": "Irele", "areas": [] },
        { "city": "Isua", "areas": [] },
        { "city": "Odigbo", "areas": [] },
        { "city": "Oka", "areas": [] },
        { "city": "Okeagbe", "areas": [] },
        { "city": "Okeigbo", "areas": [] },
        { "city": "Ose", "areas": [] }
      ]
    },
    {
      "state": "Osun",
      "cities": [
        { "city": "Ede", "areas": [] },
        { "city": "Ife", "areas": [] },
        { "city": "Ilesa", "areas": [] },
        { "city": "Olorunda-Osun", "areas": [] },
        { "city": "Osogbo", "areas": [] },
        { "city": "Aiyedade", "areas": [] },
        { "city": "Aiyedire", "areas": [] },
        { "city": "Atakumosa East", "areas": [] },
        { "city": "Atakumosa West", "areas": [] },
        { "city": "Boluwaduro", "areas": [] },
        { "city": "Boripe", "areas": [] },
        { "city": "Egbedore", "areas": [] },
        { "city": "Ifedayo", "areas": [] },
        { "city": "Ifelodun-Osun", "areas": [] },
        { "city": "Ikirun", "areas": [] },
        { "city": "Ila", "areas": [] },
        { "city": "Irepodun-Osun", "areas": [] },
        { "city": "Irewole", "areas": [] },
        { "city": "Isokan", "areas": [] },
        { "city": "Iwo", "areas": [] },
        { "city": "Obokun", "areas": [] },
        { "city": "Ola-Oluwa", "areas": [] },
        { "city": "Oriade", "areas": [] },
        { "city": "Orolu", "areas": [] }
      ]
    },
    {
      "state": "Oyo",
      "cities": [
        { "city": "Ibadan", "areas": ["Adamasingba", "Adeoyo", "Agbowo", "Agodi", "Ajibode", "Akala Express", "Akobo", "Alakia", "Alalubosa", "Apata", "Basorun", "Bodija", "CHallenge Ibadan", "Dugbe Onireke", "Eleyele", "Ibadan North West", "Ibadan Polytechnic University", "Idishin", "Ijaiye Orile", "Iwo Road", "Iyanganku", "Jericho", "Mapo", "Molete", "Moniya", "Odo Oba", "Odo Ona", "Ojoo", "Oke Ado", "Old Bodija", "Old Iyanru Ijanagang", "Ologuneru", "Olomi", "Oluyole Estate", "Omi Adio", "Pdinjo", "Rind Road", "Sabo Ibadan", "Salvation Army", "Samonda", "Soka", "Wakajaye", "Yemetu"] },
        { "city": "Akinyele", "areas": [] },
        { "city": "Egbeda", "areas": [] },
        { "city": "Ido", "areas": [] },
        { "city": "Oluyole", "areas": [] },
        { "city": "Afijio", "areas": [] },
        { "city": "Atiba", "areas": [] },
        { "city": "Atisbo", "areas": [] },
        { "city": "Ayete", "areas": [] },
        { "city": "Eruwa", "areas": [] },
        { "city": "Igbo Ora", "areas": [] },
        { "city": "Irepo", "areas": [] },
        { "city": "Iseyin", "areas": [] },
        { "city": "Itesiwaju", "areas": [] },
        { "city": "Iwajowa", "areas": [] },
        { "city": "Kajola", "areas": [] },
        { "city": "Lagelu", "areas": [] },
        { "city": "Ogbomosho North", "areas": [] },
        { "city": "Ogbomosho South", "areas": [] },
        { "city": "Ogo Oluwa", "areas": [] },
        { "city": "Olorunsogo", "areas": [] },
        { "city": "Ona-Ara", "areas": [] },
        { "city": "Orelope", "areas": [] },
        { "city": "Ori Ire", "areas": [] },
        { "city": "Oyo", "areas": [] },
        { "city": "Saki East", "areas": [] },
        { "city": "Saki West", "areas": [] },
        { "city": "Surulere-Oyo", "areas": [] }
      ]
    },
    {
      "state": "Plateau",
      "cities": [
        { "city": "Jos", "areas": [] },
        { "city": "Barkin Ladi", "areas": [] },
        { "city": "Bassa-Plateau", "areas": [] },
        { "city": "Bokkos", "areas": [] },
        { "city": "Kanam", "areas": [] },
        { "city": "Kanke", "areas": [] },
        { "city": "Langtang North", "areas": [] },
        { "city": "Langtang South", "areas": [] },
        { "city": "Mangu", "areas": [] },
        { "city": "Mikang", "areas": [] },
        { "city": "Pankshin", "areas": [] },
        { "city": "Quaan Pan", "areas": [] },
        { "city": "Riyom", "areas": [] },
        { "city": "Shendam", "areas": [] },
        { "city": "Wase", "areas": [] }
      ]
    },
    {
      "state": "Rivers",
      "cities": [
        { "city": "Eleme", "areas": [] },
        { "city": "Ikwerre", "areas": [] },
        { "city": "Obio-Akpor", "areas": [] },
        { "city": "Oyigbo", "areas": [] },
        { "city": "Port-Harcourt", "areas": [] },
        { "city": "Abua/Odual", "areas": [] },
        { "city": "Ahoada", "areas": [] },
        { "city": "Akuku Toru", "areas": [] },
        { "city": "Andoni", "areas": [] },
        { "city": "Asari-Toru", "areas": [] },
        { "city": "Bonny", "areas": [] },
        { "city": "Degema", "areas": [] },
        { "city": "Emohua", "areas": [] },
        { "city": "Etche", "areas": [] },
        { "city": "Gokana", "areas": [] },
        { "city": "Khana", "areas": [] },
        { "city": "Ogba/Egbema/Ndoni", "areas": [] },
        { "city": "Ogu/Bolo", "areas": [] },
        { "city": "Okrika", "areas": [] },
        { "city": "Omuma", "areas": [] },
        { "city": "Tai", "areas": [] }
      ]
    },
    {
      "state": "Sokoto",
      "cities": [
        { "city": "Illela", "areas": [] },
        { "city": "Sokoto North", "areas": [] },
        { "city": "Sokoto South", "areas": [] },
        { "city": "Binji", "areas": [] },
        { "city": "Bodinga", "areas": [] },
        { "city": "Dange-Shuni", "areas": [] },
        { "city": "Gada", "areas": [] },
        { "city": "Goronyo", "areas": [] },
        { "city": "Gudu LGA", "areas": [] },
        { "city": "Gwadabawa", "areas": [] },
        { "city": "Isa", "areas": [] },
        { "city": "Kebbe", "areas": [] },
        { "city": "Kware", "areas": [] },
        { "city": "Rabah", "areas": [] },
        { "city": "Sabon Birni", "areas": [] },
        { "city": "Shagari", "areas": [] },
        { "city": "Silame", "areas": [] },
        { "city": "Tambuwal", "areas": [] },
        { "city": "Tangaza", "areas": [] },
        { "city": "Tureta", "areas": [] },
        { "city": "Wamako", "areas": [] },
        { "city": "Wurno", "areas": [] },
        { "city": "Yabo", "areas": [] }
      ]
    },
    {
      "state": "Taraba",
      "cities": [
        { "city": "Jalingo", "areas": [] },
        { "city": "Takum", "areas": [] },
        { "city": "Wukari", "areas": [] },
        { "city": "Ardo-Kola", "areas": [] },
        { "city": "Bali", "areas": [] },
        { "city": "Donga", "areas": [] },
        { "city": "Gashaka", "areas": [] },
        { "city": "Gassol", "areas": [] },
        { "city": "Ibi", "areas": [] },
        { "city": "Karim-Lamido", "areas": [] },
        { "city": "Kurmi", "areas": [] },
        { "city": "Lau", "areas": [] },
        { "city": "Sardauna", "areas": [] },
        { "city": "Ussa", "areas": [] },
        { "city": "Yorro", "areas": [] },
        { "city": "Zing", "areas": [] }
      ]
    },
    {
      "state": "Yobe",
      "cities": [
        { "city": "Damaturu", "areas": [] },
        { "city": "Potiskum", "areas": [] },
        { "city": "Bade", "areas": [] },
        { "city": "Bursari", "areas": [] },
        { "city": "Fika", "areas": [] },
        { "city": "Fune", "areas": [] },
        { "city": "Geidam", "areas": [] },
        { "city": "Gujba", "areas": [] },
        { "city": "Gulani", "areas": [] },
        { "city": "Jakusko", "areas": [] },
        { "city": "Karasuwa", "areas": [] },
        { "city": "Machina", "areas": [] },
        { "city": "Nangere", "areas": [] },
        { "city": "Nguru", "areas": [] },
        { "city": "Tarmua", "areas": [] },
        { "city": "Yunusari", "areas": [] },
        { "city": "Yusufari", "areas": [] }
      ]
    },
    {
      "state": "Zamfara",
      "cities": [
        { "city": "Gusau", "areas": [] },
        { "city": "Anka", "areas": [] },
        { "city": "Bakura", "areas": [] },
        { "city": "Birnin Magaji", "areas": [] },
        { "city": "Bukkuyum", "areas": [] },
        { "city": "Bungudu", "areas": [] },
        { "city": "Gummi", "areas": [] },
        { "city": "Kaura Namoda", "areas": [] },
        { "city": "Maradun", "areas": [] },
        { "city": "Maru", "areas": [] },
        { "city": "Shinkafi", "areas": [] },
        { "city": "Talata Mafara", "areas": [] },
        { "city": "Tsafe", "areas": [] },
        { "city": "Zurmi", "areas": [] }
      ]
    },
    {
      "state": "Abuja (FCT)",
      "cities": [
        { "city": "Central Business District", "areas": [] },
        { "city": "Gwarinpa", "areas": [] },
        { "city": "Kubwa", "areas": [] },
        { "city": "Wuse", "areas": [] },
        { "city": "Wuse 2", "areas": [] },
        { "city": "Abaji", "areas": [] },
        { "city": "Apo District", "areas": [] },
        { "city": "Asokoro", "areas": [] },
        { "city": "Bwari", "areas": [] },
        { "city": "Dakibiyu", "areas": [] },
        { "city": "Dakwo District", "areas": [] },
        { "city": "Dei-Dei", "areas": [] },
        { "city": "Duboyi", "areas": [] },
        { "city": "Durumi", "areas": [] },
        { "city": "Dutse-Alhaji", "areas": [] },
        { "city": "Gaduwa", "areas": [] },
        { "city": "Galadimawa", "areas": [] },
        { "city": "Garki 1", "areas": [] },
        { "city": "Garki 2", "areas": [] },
        { "city": "Gudu", "areas": [] },
        { "city": "Guzape District", "areas": [] },
        { "city": "Gwagwa", "areas": [] },
        { "city": "Gwagwalada", "areas": [] },
        { "city": "Idu Industrial", "areas": [] },
        { "city": "Jabi", "areas": [] },
        { "city": "Jahi", "areas": [] },
        { "city": "Jikwoyi", "areas": [] },
        { "city": "Jiwa", "areas": [] },
        { "city": "Kabusa", "areas": [] },
        { "city": "Kado", "areas": [] },
        { "city": "Karmo", "areas": [] },
        { "city": "Karshi", "areas": [] },
        { "city": "Karu", "areas": [] },
        { "city": "Katampe", "areas": [] },
        { "city": "Kaura", "areas": [] },
        { "city": "Kpeyegyi", "areas": [] },
        { "city": "Kuchigoro", "areas": [] },
        { "city": "Kuje", "areas": [] },
        { "city": "Kurudu", "areas": [] },
        { "city": "Kwali", "areas": [] },
        { "city": "Lokogoma", "areas": [] },
        { "city": "Lugbe District", "areas": [] },
        { "city": "Mabushi", "areas": [] },
        { "city": "Maitama", "areas": [] },
        { "city": "Mararaba", "areas": [] },
        { "city": "Masaka", "areas": [] },
        { "city": "Mbora", "areas": [] },
        { "city": "Mpape", "areas": [] },
        { "city": "Nyanya", "areas": [] },
        { "city": "Okanje", "areas": [] },
        { "city": "Orozo", "areas": [] },
        { "city": "Pyakasa", "areas": [] },
        { "city": "Sabo Gida", "areas": [] },
        { "city": "Utako", "areas": [] },
        { "city": "Wumba", "areas": [] },
        { "city": "Wuye", "areas": [] },
        { "city": "Zuba", "areas": [] }
      ]
    }
  ]
};
